name: Build
on: [push]
jobs:
  build-core:
    name: Build Core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Gradle Script Executable Flag
        run: chmod a+x ./gradlew
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: core::build
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Gradle Script Executable Flag
        run: chmod a+x ./gradlew
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: console-client::build
